network:
  version: 2
  renderer: networkd

  ethernets:
    enp0s3:
      dhcp4: no

  vlans:
    vlan10:
      id: 10
      link: enp0s3
      addresses:
        - 192.168.10.5/24
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.10.1

    vlan20:
      id: 20
      link: enp0s3
      addresses:
        - 10.10.20.5/24
      routing-policy:
        - to: 10.10.30.0/24
          table: 100
      routes:
        - to: 10.10.30.0/24
          via: 10.10.20.1
          table: 100
